# 定义变量
TCPL = TheCProgrammingLanguage
clean:
	rm -rf *.out *.o
cha1-2:$(TCPL)/chapter1-2.cpp
	gcc -g -o cha1-2.out $(TCPL)/chapter1-2.cpp
cha1-3:$(TCPL)/chapter1-3.cpp
	gcc -g -o cha1-3.out $(TCPL)/chapter1-3.cpp
cha1-4:$(TCPL)/chapter1-4.cpp
	gcc -g -o cha1-4.out $(TCPL)/chapter1-4.cpp
cha1-5-1:$(TCPL)/chapter1-5-1.cpp
	gcc -g -o cha1-5-1.out $(TCPL)/chapter1-5-1.cpp
cha1-5-4:$(TCPL)/chapter1-5-4.cpp
	gcc -g -o cha1-5-4.out $(TCPL)/chapter1-5-4.cpp